# Generated by Django 4.2.3 on 2024-07-15 21:36

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[news.validators.validate_length_title],
            ),
        ),
    ]
