# Generated by Django 4.2.3 on 2024-07-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(auto_created=True),
        ),
    ]
